apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: cd-template
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
  - name: git-repo-name
    description: The name of the deployment to be created / patched

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: cd-pipeline-$(tt.params.git-repo-name)-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: cd-pipeline
      params:
      - name: git-url
        value: $(tt.params.git-repo-url)
      - name: git-ref
        value: $(tt.params.git-revision)
      - name: image-name
        value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(tt.params.git-repo-name):$(tt.params.git-revision)
      - name: app-name
        value: $(tt.params.git-repo-name)
      workspaces:
      - name: pipeline-workspace
        persistentVolumeClaim:
          claimName: pipeline-workspace