apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - description: The URL of the git repository to clone
      name: git-url
      type: string
    - default: master
      description: The branch or ref to checkout
      name: git-ref
      type: string
    - description: The name of the image to build and deploy
      name: image-name
      type: string
    - description: The name of the application to deploy
      name: app-name
      type: string
    - default: 'http://inventory:8080'
      description: The base URL of the deployed service for BDD tests
      name: base-url
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-ref)
      taskRef:
        kind: Task
        name: checkout
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: pylint
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: testing
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.image-name)
      runAfter:
        - pylint
        - testing
      taskRef:
        kind: Task
        name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: deploy
      params:
        - name: IMAGE
          value: $(params.image-name)
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: deploy
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: behave
      params:
        - name: base-url
          value: $(params.base-url)
      runAfter:
        - deploy
      taskRef:
        kind: Task
        name: behave
      workspaces:
        - name: source
          workspace: pipeline-workspace
  workspaces:
    - description: Shared workspace for all tasks
      name: pipeline-workspace
