---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo
spec:
  description: This task simply echoes a message
  params:
    - name: message
      description: The message to echo
      type: string
  steps:
    - name: echo-message
      image: alpine:3
      command: [/bin/echo]
      args: ["$(params.message)"]

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: checkout
spec:
  description: Clone the code repository to the workspace
  workspaces:
    - name: source
      description: The git repo will be cloned onto the volume backing this workspace
  params:
    - name: url
      description: git url to clone
      type: string
    - name: revision
      description: git revision to checkout (branch, tag, sha, ref…)
      type: string
      default: master
  steps:
    - name: clone
      image: alpine:3.19
      securityContext:
        runAsUser: 0
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -ex
        apk add --no-cache git
        git clone --depth 1 --branch $(params.revision) $(params.url) /tmp/repo-clone
        cp -r /tmp/repo-clone/* $(workspaces.source.path)/
        echo "Workspace after clone:"
        ls -R $(workspaces.source.path)



---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint
spec:
  description: Run linting checks on the Python code
  workspaces:
    - name: source
      description: The workspace containing the source code
  params:
    - name: args
      description: Arguments to pass to the linter
      type: array
      default: ["run"]
    - name: image
      description: The image providing the linting tools
      type: string
      default: "python:3.11-slim"
  steps:
    - name: lint
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e

        echo "PWD is:"
        pwd
        echo "Contents of workingDir:"
        ls -R

        echo "Installing linting dependencies..."
        pip install --upgrade pip
        pip install flake8 pylint

        echo "Running flake8 on entire repo..."
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

        echo "Running pylint on entire repo..."
        pylint . --max-line-length=127

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tests
spec:
  description: Run unit tests on the Python code
  workspaces:
    - name: source
      description: The workspace containing the source code
  params:
    - name: args
      description: Arguments to pass to pytest
      type: array
      default: ["run"]
    - name: image
      description: The image providing the testing tools
      type: string
      default: "python:3.11-slim"
    - name: database_uri
      description: Database URI for testing
      type: string
      # ✅ Use SQLite in the CI container
      default: "sqlite:///inventory_test.db"
  steps:
    - name: tests
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      env:
        - name: DATABASE_URI
          value: $(params.database_uri)
      script: |
        #!/bin/bash
        set -e

        echo "=== PWD ==="
        pwd
        echo "=== Initial workspace contents ==="
        ls -la || true

        # If the workspace doesn't have the repo yet, clone it directly here
        if [ ! -f Pipfile ]; then
          echo "Pipfile not found – workspace appears empty. Cloning repo directly into workspace..."

          echo "Installing git and system deps..."
          apt-get update -qq && apt-get install -y git gcc libpq-dev postgresql-client

          REPO_URL="https://github.com/CSCI-GA-2820-FA25-001/inventory"
          BRANCH="master"

          TEMP_DIR="/tmp/repo-clone"
          rm -rf "$TEMP_DIR"

          echo "Cloning $REPO_URL (branch: $BRANCH) into $TEMP_DIR..."
          git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$TEMP_DIR"

          echo "Copying repo contents into workspace $(workspaces.source.path)..."
          cp -r "$TEMP_DIR"/* "$(workspaces.source.path)/"

          echo "=== Workspace contents after clone ==="
          ls -la
        else
          echo "Pipfile found – assuming source code is already present."
          echo "Installing system deps..."
          apt-get update -qq && apt-get install -y gcc libpq-dev postgresql-client
        fi

        if [ ! -f Pipfile ]; then
          echo "ERROR: Pipfile still not found after clone. Aborting."
          exit 1
        fi

        echo "Installing pipenv..."
        pip install --upgrade pip pipenv

        if [ ! -f Pipfile.lock ]; then
          echo "Pipfile.lock not found – creating lockfile with 'pipenv lock'..."
          pipenv lock
        fi

        if [ ! -f Pipfile.lock ]; then
          echo "ERROR: Pipfile.lock still not found after 'pipenv lock'. Aborting."
          ls -la
          exit 1
        fi

        echo "Syncing project dependencies from Pipfile.lock into system env..."
        if ! pipenv sync --dev --system; then
          echo "pipenv sync failed, falling back to 'pipenv install --dev --system'..."
          pipenv install --dev --system
        fi

        echo "Running unit tests with coverage (DATABASE_URI=${DATABASE_URI})..."
        export RETRY_COUNT=1
        pytest --pspec --cov=service --cov-fail-under=95 --disable-warnings

        echo "Tests completed successfully!"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  description: Trigger an OpenShift BuildConfig to build the image
  workspaces:
    - name: source
      description: (not used by this task, but kept for pipeline compatibility)
  params:
    - name: IMAGE
      description: Fully qualified image reference (must match BuildConfig output)
      type: string
  results:
    - name: IMAGE_DIGEST
      description: Placeholder digest (not actually computed)
  steps:
    - name: start-oc-build
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/bash
        set -e

        echo "Starting OpenShift BuildConfig 'inventory-build'..."
        oc start-build inventory-build --wait --follow

        echo "Build finished successfully."
        # We’re not computing a real digest; just write a dummy value
        echo "sha256:dummy" > "$(results.IMAGE_DIGEST.path)"


---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  description: Deploy the application to OpenShift
  workspaces:
    - name: source
      description: The workspace containing the k8s manifests
  params:
    - name: IMAGE
      description: The image reference to deploy
      type: string
    - name: APP_NAME
      description: The name of the application
      type: string
      default: inventory
    - name: MANIFEST_DIR
      description: Directory containing kubernetes manifests
      type: string
      default: "k8s"
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        
        echo "Deploying to OpenShift..."
        echo "Current working directory: $(pwd)"
        echo "Workspace contents:"
        ls -R
        
        echo "Ensuring PostgreSQL is deployed..."
        oc apply -f $(params.MANIFEST_DIR)/postgres/ || true
        
        echo "Applying service..."
        oc apply -f $(params.MANIFEST_DIR)/service.yaml
        
        echo "Applying route..."
        oc apply -f $(params.MANIFEST_DIR)/route.yaml
        
        echo "Applying deployment..."
        oc apply -f $(params.MANIFEST_DIR)/deployment.yaml
        
        # Update the deployment image to the one just built
        echo "Updating deployment with image $(params.IMAGE)..."
        oc set image deployment/$(params.APP_NAME) $(params.APP_NAME)=$(params.IMAGE)
        
        echo "Waiting for deployment to complete..."
        oc rollout status deployment/$(params.APP_NAME) --timeout=5m
        
        echo "Getting route URL..."
        ROUTE_URL=$(oc get route $(params.APP_NAME) -o jsonpath='{.spec.host}')
        echo "Application available at: http://$ROUTE_URL"
        
        echo "Deployment completed successfully!"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: behave
spec:
  description: Run BDD tests using Behave against the deployed service
  workspaces:
    - name: source
      description: The workspace containing the BDD test features
  params:
    - name: base-url
      description: The base URL of the deployed service to test against
      type: string
    - name: driver
      description: The web driver to use for Selenium tests
      type: string
      default: "chrome"
    - name: wait-seconds
      description: Number of seconds to wait for the service to be ready
      type: string
      default: "60"
  steps:
    - name: wait-for-service
      image: cluster-registry:5001/inventory:1.0   # 👈 no $(params.APP_NAME) here
      securityContext:
        runAsUser: 0
      script: |
        #!/bin/bash
        set -e
        
        echo "Installing curl..."
        apt-get update -qq && apt-get install -y curl
        
        echo "Waiting for service to be ready at $(params.base-url)..."
        
        WAIT_TIME=$(params.wait-seconds)
        COUNTER=0
        
        HOST=$(echo $(params.base-url) | sed 's|http://||' | sed 's|https://||' | cut -d: -f1)
        echo "Using Host header: $HOST"
        
        until curl -f $(params.base-url)/health || [ $COUNTER -eq $WAIT_TIME ]; do
          echo "Waiting for service... ($COUNTER/$WAIT_TIME)"
          sleep 1
          COUNTER=$((COUNTER+1))
        done
        
        if [ $COUNTER -eq $WAIT_TIME ]; then
          echo "Service did not become ready in time"
          exit 1
        fi
        
        echo "Service is ready!"
    
    - name: run-behave-tests
      image: cluster-registry:5001/inventory:1.0
      securityContext:
        runAsUser: 0
      workingDir: $(workspaces.source.path)
      env:
        - name: BASE_URL
          value: $(params.base-url)
        - name: DRIVER
          value: $(params.driver)
      script: |
        #!/bin/bash
        set -e
        
        echo "Installing test dependencies..."
        apt-get update && apt-get install -y chromium chromium-driver gcc libpq-dev
        
        echo "Installing Python test packages..."
        pip install --upgrade pip pipenv
        
        echo "Installing project dependencies with pipenv..."
        pipenv install --dev --system
        
        echo "Running Behave tests against $(params.base-url)..."
        echo "BASE_URL is set to: $BASE_URL"
        
        behave --format=pretty --tags=-wip --no-capture --no-capture-stderr
        
        echo "BDD tests completed successfully!"
